// This code is autogenerated. Please, do not edit this file.
package sdf.kira_generated_suppliers

import com.popovanton0.kira.suppliers.enum
import com.popovanton0.kira.suppliers.nullableEnum
import com.popovanton0.kira.suppliers.string
import com.popovanton0.kira.suppliers.nullableString
import com.popovanton0.kira.suppliers.boolean
import com.popovanton0.kira.suppliers.nullableBoolean
import com.popovanton0.kira.suppliers.compound.compound
import com.popovanton0.kira.suppliers.compound.nullableCompound
import com.popovanton0.kira.suppliers.compound.compound
import com.popovanton0.kira.suppliers.string
import com.popovanton0.kira.suppliers.compound.nullableCompound
import com.popovanton0.kira.suppliers.string
import com.popovanton0.kira.suppliers.boolean

public fun ExampleFunction3RootSupplier() = com.popovanton0.kira.suppliers.compound.root() {
    val ds1 = enum<sdf.Quality>(paramName = "ds1")
    val ds2 = nullableEnum<sdf.Quality?>(paramName = "ds2", defaultValue = null)
    val ds3 = string(paramName = "name", defaultValue = "Example")
    val ds4 = nullableString(paramName = "name", defaultValue = null)
    val ds5 = boolean(paramName = "name", defaultValue = false)
    val ds6 = nullableBoolean(paramName = "name", defaultValue = null)
    val ds7 = compound<sdf.Rock>(
        paramName = "ds7",
        label = "sdf.Rock"
    ) {
        injector {
            sdf.Rock
        }
    }
    val ds8 = nullableCompound<sdf.Rock>(
        paramName = "ds8",
        label = "sdf.Rock",
        isNullByDefault = true
    ) {
        injector {
            sdf.Rock
        }
    }
    val ds9 = compound<sdf.Engine>(
        paramName = "ds9",
        label = "sdf.Engine"
    ) {
        val model = string(paramName = "name", defaultValue = "Example")
        val diesel = nullableCompound<sdf.Engine2>(
            paramName = "diesel",
            label = "sdf.Engine2",
            isNullByDefault = true
        ) {
            val adsad = string(paramName = "name", defaultValue = "Example")
            val hnghgj = boolean(paramName = "name", defaultValue = false)
            
            injector {
                sdf.Engine2(
                    adsad = adsad.currentValue(),
                    hnghgj = hnghgj.currentValue()
                )
            }
        }
        
        injector {
            sdf.Engine(
                model = model.currentValue(),
                diesel = diesel.currentValue()
            )
        }
    }
    
    injector {
        sdf.ExampleFunction3(
            ds1 = ds1.currentValue(),
            ds2 = ds2.currentValue(),
            ds3 = ds3.currentValue(),
            ds4 = ds4.currentValue(),
            ds5 = ds5.currentValue(),
            ds6 = ds6.currentValue(),
            ds7 = ds7.currentValue(),
            ds8 = ds8.currentValue(),
            ds9 = ds9.currentValue()
        )
    }
}
