// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.sdf1

import com.popovanton0.kira.suppliers.*
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.compound.CompoundSupplierBuilder
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.KiraScope
import com.popovanton0.kira.suppliers.compound.NullableCompoundSupplierBuilder
import sdf1.ExampleFunction3
import sdf1.Quality
import sdf1.Rock

public class Kira_ExampleFunction3 : KiraProvider<ExampleFunction3Scope> {
  public override val kira: Kira<ExampleFunction3Scope> = kira(ExampleFunction3Scope()) {
    ds1 = `enum`(paramName = "ds1")
    ds2 = nullableEnum(paramName = "ds2", defaultValue = null)
    ds3 = string(paramName = "ds3", defaultValue = "Lorem")
    ds4 = nullableString(paramName = "ds4", defaultValue = null)
    ds5 = boolean(paramName = "ds5", defaultValue = false)
    ds6 = nullableBoolean(paramName = "ds6", defaultValue = null)
    ds7 = singleValue(
      paramName = "ds7",
      value = Rock,
      typeName = "sdf1.Rock",
    )

    ds8 = nullableSingleValue(
      paramName = "ds8",
      value = Rock,
      typeName = "sdf1.Rock",
      nullByDefault = true
    )

    injector {
      ExampleFunction3(
        ds1 = ds1.currentValue(),
        ds2 = ds2.currentValue(),
        ds3 = ds3.currentValue(),
        ds4 = ds4.currentValue(),
        ds5 = ds5.currentValue(),
        ds6 = ds6.currentValue(),
        ds7 = ds7.currentValue(),
        ds8 = ds8.currentValue(),
      )
    }
  }

}

public class ExampleFunction3Scope :
    GeneratedKiraScopeWithImpls<ExampleFunction3Scope.SupplierImplsScope>() {
  public override val supplierImplsScope: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var ds1: Supplier<Quality>

  public lateinit var ds2: Supplier<Quality?>

  public lateinit var ds3: Supplier<String>

  public lateinit var ds4: Supplier<String?>

  public lateinit var ds5: Supplier<Boolean>

  public lateinit var ds6: Supplier<Boolean?>

  public lateinit var ds7: Supplier<Rock>

  public lateinit var ds8: Supplier<Rock?>

  public override fun collectSuppliers(): List<Supplier<*>> = listOf(ds1, ds2, ds3, ds4, ds5, ds6,
      ds7, ds8, )

  public class SupplierImplsScope(
    private val scope: ExampleFunction3Scope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope() {
    public var ds1: EnumSupplierBuilder<Quality>
      get() = scope.ds1 as? EnumSupplierBuilder<Quality> ?: implChanged()
      set(`value`) {
        scope.ds1 = value
      }

    public var ds2: NullableEnumSupplierBuilder<Quality?>
      get() = scope.ds2 as? NullableEnumSupplierBuilder<Quality?> ?: implChanged()
      set(`value`) {
        scope.ds2 = value
      }

    public var ds3: StringSupplierBuilder
      get() = scope.ds3 as? StringSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.ds3 = value
      }

    public var ds4: NullableStringSupplierBuilder
      get() = scope.ds4 as? NullableStringSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.ds4 = value
      }

    public var ds5: BooleanSupplierBuilder
      get() = scope.ds5 as? BooleanSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.ds5 = value
      }

    public var ds6: NullableBooleanSupplierBuilder
      get() = scope.ds6 as? NullableBooleanSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.ds6 = value
      }

    public var ds7: CompoundSupplierBuilder<Rock, KiraScope>
      get() = scope.ds7 as? CompoundSupplierBuilder<Rock, KiraScope> ?: implChanged()
      set(`value`) {
        scope.ds7 = value
      }

    public var ds8: NullableCompoundSupplierBuilder<Rock, KiraScope>
      get() = scope.ds8 as? NullableCompoundSupplierBuilder<Rock, KiraScope> ?: implChanged()
      set(`value`) {
        scope.ds8 = value
      }
  }
}
