// This code is autogenerated. Please, do not edit this file.
package sdf.kira_generated_suppliers

import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls.SupplierImplsScope
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.enum
import com.popovanton0.kira.suppliers.nullableEnum
import com.popovanton0.kira.suppliers.string
import com.popovanton0.kira.suppliers.nullableString
import com.popovanton0.kira.suppliers.boolean
import com.popovanton0.kira.suppliers.nullableBoolean
import com.popovanton0.kira.suppliers.compound.compound
import com.popovanton0.kira.suppliers.compound.nullableCompound
import com.popovanton0.kira.suppliers.string

public class Sdf_ExampleFunction3Scope : GeneratedKiraScopeWithImpls<Sdf_ExampleFunction3Scope.SupplierImplsScope>() {

    public lateinit var ds1: Supplier<sdf.Quality>
    public lateinit var ds2: Supplier<sdf.Quality?>
    public lateinit var ds3: Supplier<kotlin.String>
    public lateinit var ds4: Supplier<kotlin.String?>
    public lateinit var ds5: Supplier<kotlin.Boolean>
    public lateinit var ds6: Supplier<kotlin.Boolean?>
    public lateinit var ds7: Supplier<sdf.Rock>
    public lateinit var ds8: Supplier<sdf.B?>
    public lateinit var ds9: Supplier<sdf.A>
    public lateinit var ds10: Supplier<sdf.Engine?>

    override val supplierImplsScope: SupplierImplsScope = SupplierImplsScope(this)

    public class SupplierImplsScope(private val scope: Sdf_ExampleFunction3Scope): GeneratedKiraScopeWithImpls.SupplierImplsScope() {

        public var ds1: com.popovanton0.kira.suppliers.EnumSupplierBuilder<sdf.Quality>
            get() = scope.ds1 as? com.popovanton0.kira.suppliers.EnumSupplierBuilder<sdf.Quality> ?: implChanged()
            set(value) { scope.ds1 = value }
        
        public var ds2: com.popovanton0.kira.suppliers.NullableEnumSupplierBuilder<sdf.Quality?>
            get() = scope.ds2 as? com.popovanton0.kira.suppliers.NullableEnumSupplierBuilder<sdf.Quality?> ?: implChanged()
            set(value) { scope.ds2 = value }
        
        public var ds3: com.popovanton0.kira.suppliers.StringSupplierBuilder
            get() = scope.ds3 as? com.popovanton0.kira.suppliers.StringSupplierBuilder ?: implChanged()
            set(value) { scope.ds3 = value }
        
        public var ds4: com.popovanton0.kira.suppliers.NullableStringSupplierBuilder
            get() = scope.ds4 as? com.popovanton0.kira.suppliers.NullableStringSupplierBuilder ?: implChanged()
            set(value) { scope.ds4 = value }
        
        public var ds5: com.popovanton0.kira.suppliers.BooleanSupplierBuilder
            get() = scope.ds5 as? com.popovanton0.kira.suppliers.BooleanSupplierBuilder ?: implChanged()
            set(value) { scope.ds5 = value }
        
        public var ds6: com.popovanton0.kira.suppliers.NullableBooleanSupplierBuilder
            get() = scope.ds6 as? com.popovanton0.kira.suppliers.NullableBooleanSupplierBuilder ?: implChanged()
            set(value) { scope.ds6 = value }
        
        public var ds7: com.popovanton0.kira.suppliers.compound.CompoundSupplierBuilder<sdf.Rock, *>
            get() = scope.ds7 as? com.popovanton0.kira.suppliers.compound.CompoundSupplierBuilder<sdf.Rock, *> ?: implChanged()
            set(value) { scope.ds7 = value }
        
        public var ds10: com.popovanton0.kira.suppliers.compound.NullableCompoundSupplierBuilder<sdf.Engine, Sdf_ExampleFunction3Scope.Ds10Scope>
            get() = scope.ds10 as? com.popovanton0.kira.suppliers.compound.NullableCompoundSupplierBuilder<sdf.Engine, Sdf_ExampleFunction3Scope.Ds10Scope> ?: implChanged()
            set(value) { scope.ds10 = value }
        
    }

    override fun collectSuppliers(): List<Supplier<*>> = listOf(ds1, ds2, ds3, ds4, ds5, ds6, ds7, ds10, )

    public class Sdf_ExampleFunction3Scope.Ds10Scope() : GeneratedKiraScopeWithImpls<Sdf_ExampleFunction3Scope.Ds10Scope.SupplierImplsScope>() {
    
        public lateinit var model: Supplier<kotlin.String>
        public lateinit var engine2: Supplier<sdf.Engine2?>
        public lateinit var sdf: Supplier<sdf.A?>
    
        override val supplierImplsScope: SupplierImplsScope = SupplierImplsScope(this)
    
        public class SupplierImplsScope(private val scope: Sdf_ExampleFunction3Scope.Ds10Scope): GeneratedKiraScopeWithImpls.SupplierImplsScope() {
    
            public var model: com.popovanton0.kira.suppliers.StringSupplierBuilder
                get() = scope.model as? com.popovanton0.kira.suppliers.StringSupplierBuilder ?: implChanged()
                set(value) { scope.model = value }
        
        }
    
        override fun collectSuppliers(): List<Supplier<*>> = listOf(model, )
    
    }
    
}

public data class ExampleFunction3Misses(
    val ds8: Supplier<sdf.B?>,
    val ds9: Supplier<sdf.A>,
    val ds10: ExampleFunction3Misses.Ds10Misses,
) {
    public data class Ds10Misses(
        val engine2: Supplier<sdf.Engine2?>,
        val sdf: Supplier<sdf.A?>,
    ) {
    }
    
}

public fun ExampleFunction3RootSupplier(
    misses: ExampleFunction3Misses
) = com.popovanton0.kira.suppliers.compound.root(
    scope = Sdf_ExampleFunction3Scope(),
) {
    this.ds1 = enum<sdf.Quality>(paramName = "ds1")
    this.ds2 = nullableEnum<sdf.Quality?>(paramName = "ds2", defaultValue = null)
    this.ds3 = string(paramName = "ds3", defaultValue = "Example")
    this.ds4 = nullableString(paramName = "ds4", defaultValue = null)
    this.ds5 = boolean(paramName = "ds5", defaultValue = false)
    this.ds6 = nullableBoolean(paramName = "ds6", defaultValue = null)
    this.ds7 = compound<sdf.Rock>(
        paramName = "ds7",
        label = "sdf.Rock"
    ) {
        injector {
            sdf.Rock
        }
    }
    this.ds8 = misses.ds8
    this.ds9 = misses.ds9
    this.ds10 = nullableCompound<sdf.Engine>(
        scope = Sdf_ExampleFunction3Scope.Ds10Scope(),
        paramName = "ds10",
        label = "sdf.Engine",
        isNullByDefault = true
    ) {
        this.model = string(paramName = "model", defaultValue = "Example")
        this.engine2 = misses.ds10.engine2
        this.sdf = misses.ds10.sdf
        
        injector {
            sdf.Engine(
                model = this.model.currentValue(),
                engine2 = this.engine2.currentValue(),
                sdf = this.sdf.currentValue()
            )
        }
    }
    
    injector {
        sdf.ExampleFunction3(
            ds1 = this.ds1.currentValue(),
            ds2 = this.ds2.currentValue(),
            ds3 = this.ds3.currentValue(),
            ds4 = this.ds4.currentValue(),
            ds5 = this.ds5.currentValue(),
            ds6 = this.ds6.currentValue(),
            ds7 = this.ds7.currentValue(),
            ds8 = this.ds8.currentValue(),
            ds9 = this.ds9.currentValue(),
            ds10 = this.ds10.currentValue()
        )
    }
}
