// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.functions_with_strange_names

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.SupplierBuilder
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_injector() : KiraProvider<injectorScope> {
  public override val kira: Kira<injectorScope> = kira(injectorScope()) {
    injector {
      functions_with_strange_names.injector(
      )
    }
  }

}

public class injectorScope : GeneratedKiraScopeWithImpls<injectorScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public override fun collectSupplierBuilders(): List<SupplierBuilder<*>> = listOf()

  public class SupplierImplsScope(
    private val scope: injectorScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
