// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.functions_with_strange_names

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraMisses
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.SupplierBuilder
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.KiraScope
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import functions_with_strange_names.misses
import kotlin.Throwable
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_misses(
  private val missesProvider: KiraScope.() -> Misses,
) : KiraProvider<missesScope> {
  private val misses: Misses = KiraScope().missesProvider()

  public override val kira: Kira<missesScope> = kira(missesScope()) {
    sdf = this@Kira_misses.misses.sdf
    injector {
      misses(
        sdf = this@Kira_misses.misses.sdf.build().currentValue(),
      )
    }
  }


  public data class Misses(
    public val sdf: SupplierBuilder<Throwable>,
  ) : KiraMisses
}

public class missesScope : GeneratedKiraScopeWithImpls<missesScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var sdf: SupplierBuilder<Throwable>

  public override fun collectSupplierBuilders(): List<SupplierBuilder<*>> = listOf(sdf, )

  public class SupplierImplsScope(
    private val scope: missesScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
