// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.functions_with_strange_names

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_kira() : KiraProvider<kiraScope> {
  public override val kira: Kira<kiraScope> = kira(kiraScope()) {
    injector {
      functions_with_strange_names.kira(
      )
    }
  }

}

public class kiraScope : GeneratedKiraScopeWithImpls<kiraScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public override fun collectSuppliers(): List<Supplier<*>> = listOf()

  public class SupplierImplsScope(
    private val scope: kiraScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
