// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.functions_with_strange_names

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import functions_with_strange_names.string
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_string() : KiraProvider<stringScope> {
  public override val kira: Kira<stringScope> = kira(stringScope()) {
    injector {
      string(
      )
    }
  }

}

public class stringScope : GeneratedKiraScopeWithImpls<stringScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public override fun collectSuppliers(): List<Supplier<*>> = listOf()

  public class SupplierImplsScope(
    private val scope: stringScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
