// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.functions_with_scope_param_name

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.StringSupplierBuilder
import com.popovanton0.kira.suppliers.base.SupplierBuilder
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import com.popovanton0.kira.suppliers.string
import functions_with_scope_param_name.ExampleFunction2
import kotlin.String
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_ExampleFunction2() : KiraProvider<ExampleFunction2Scope> {
  public override val kira: Kira<ExampleFunction2Scope> = kira(ExampleFunction2Scope()) {
    `scope$` = string(paramName = "scope${'$'}", defaultValue = "Lorem")
    injector {
      ExampleFunction2(
        `scope$` = `scope$`.build().currentValue(),
      )
    }
  }

}

public class ExampleFunction2Scope :
    GeneratedKiraScopeWithImpls<ExampleFunction2Scope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var `scope$`: SupplierBuilder<String>

  public override fun collectSupplierBuilders(): List<SupplierBuilder<*>> = listOf(`scope$`, )

  public class SupplierImplsScope(
    private val scope: ExampleFunction2Scope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope() {
    public var `scope$`: StringSupplierBuilder
      get() = scope.`scope$` as? StringSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.`scope$` = value
      }
  }
}
