// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.function_in_class

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.Injector
import com.popovanton0.kira.suppliers.kira

/**
 * @param injector wasn't generated because:
 *  - Function is not top level, thus containing class instance is needed
 */
public class Kira_ExampleFunction(
  public val injector: ExampleFunctionScope.() -> Injector<Unit>,
) : KiraProvider<ExampleFunctionScope> {
  public override val kira: Kira<ExampleFunctionScope> = kira(ExampleFunctionScope()) {
    injector()
  }

}

public class ExampleFunctionScope :
    GeneratedKiraScopeWithImpls<ExampleFunctionScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public override fun collectSuppliers(): List<Supplier<*>> = listOf()

  public class SupplierImplsScope(
    private val scope: ExampleFunctionScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
