// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.registry_generation

import com.popovanton0.kira.suppliers.BooleanSupplierBuilder
import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.StringSupplierBuilder
import com.popovanton0.kira.suppliers.base.Supplier
import com.popovanton0.kira.suppliers.boolean
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import com.popovanton0.kira.suppliers.string
import kotlin.Boolean
import kotlin.String
import kotlin.collections.List
import kotlin.collections.listOf
import registry_generation.ExampleFunction2

public class Kira_ExampleFunction2() : KiraProvider<ExampleFunction2Scope> {
  public override val kira: Kira<ExampleFunction2Scope> = kira(ExampleFunction2Scope()) {
    sdf = string(paramName = "sdf", defaultValue = "Lorem")
    asd = boolean(paramName = "asd", defaultValue = false)
    injector {
      ExampleFunction2(
        sdf = sdf.currentValue(),
        asd = asd.currentValue(),
      )
    }
  }

}

public class ExampleFunction2Scope :
    GeneratedKiraScopeWithImpls<ExampleFunction2Scope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var sdf: Supplier<String>

  public lateinit var asd: Supplier<Boolean>

  public override fun collectSuppliers(): List<Supplier<*>> = listOf(sdf, asd, )

  public class SupplierImplsScope(
    private val scope: ExampleFunction2Scope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope() {
    public var sdf: StringSupplierBuilder
      get() = scope.sdf as? StringSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.sdf = value
      }

    public var asd: BooleanSupplierBuilder
      get() = scope.asd as? BooleanSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.asd = value
      }
  }
}
