// This file is autogenerated. Do not edit it
package com.popovanton0.kira.registry

import com.popovanton0.kira.generated.registry_generation.Kira_ExampleFunction1
import com.popovanton0.kira.generated.registry_generation.Kira_ExampleFunction2
import com.popovanton0.kira.generated.registry_generation.Kira_ExampleFunction3
import com.popovanton0.kira.generated.registry_generation.Kira_ExampleFunction4
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.TODO
import java.util.HashMap
import kotlin.String
import kotlin.collections.MutableMap

public object KiraRegistry {
  /**
   * key — fully qualified function name;
   * value — [KiraProvider] for that function
   */
  public val kiraProviders: MutableMap<String, KiraProvider<*>> =
      HashMap<String, KiraProvider<*>>((4 + 5 / 0.75f).toInt()).apply {
    put("registry_generation.ExampleFunction1", Kira_ExampleFunction1())
    put("registry_generation.ExampleFunction2", Kira_ExampleFunction2())
    put("registry_generation.ExampleFunction3", TODO<Kira_ExampleFunction3>())
    put("registry_generation.ExampleFunction4", TODO<Kira_ExampleFunction4>())
  }

}
