// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.function_with_composable_lambda_params

import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraMisses
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.SupplierBuilder
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.KiraScope
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import function_with_composable_lambda_params.Composable
import function_with_composable_lambda_params.ExampleFunction
import kotlin.Boolean
import kotlin.Function0
import kotlin.Function2
import kotlin.Int
import kotlin.String
import kotlin.Unit
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_ExampleFunction(
  private val missesProvider: KiraScope.() -> Misses,
) : KiraProvider<ExampleFunctionScope> {
  private val misses: Misses = KiraScope().missesProvider()

  public override val kira: Kira<ExampleFunctionScope> = kira(ExampleFunctionScope()) {
    param1 = this@Kira_ExampleFunction.misses.param1
    param2 = this@Kira_ExampleFunction.misses.param2
    param3 = this@Kira_ExampleFunction.misses.param3
    param4 = this@Kira_ExampleFunction.misses.param4
    injector {
      ExampleFunction(
        param1 = this@Kira_ExampleFunction.misses.param1.build().currentValue(),
        param2 = this@Kira_ExampleFunction.misses.param2.build().currentValue(),
        param3 = this@Kira_ExampleFunction.misses.param3.build().currentValue(),
        param4 = this@Kira_ExampleFunction.misses.param4.build().currentValue(),
      )
    }
  }


  public data class Misses(
    public val param1: SupplierBuilder<@Composable Function0<Unit>>,
    public val param2: SupplierBuilder<@Composable Function2<Int, String, Unit>>,
    public val param3: SupplierBuilder<@Composable Function0<Boolean>>,
    public val param4: SupplierBuilder<@Composable Function2<Int, String, Boolean>>,
  ) : KiraMisses
}

public class ExampleFunctionScope :
    GeneratedKiraScopeWithImpls<ExampleFunctionScope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var param1: SupplierBuilder<@Composable Function0<Unit>>

  public lateinit var param2: SupplierBuilder<@Composable Function2<Int, String, Unit>>

  public lateinit var param3: SupplierBuilder<@Composable Function0<Boolean>>

  public lateinit var param4: SupplierBuilder<@Composable Function2<Int, String, Boolean>>

  public override fun collectSupplierBuilders(): List<SupplierBuilder<*>> = listOf(param1, param2,
      param3, param4, )

  public class SupplierImplsScope(
    private val scope: ExampleFunctionScope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope()
}
