// This file is autogenerated. Do not edit it
package com.popovanton0.kira.generated.external_functions

import com.popovanton0.kira.suppliers.BooleanSupplierBuilder
import com.popovanton0.kira.suppliers.Kira
import com.popovanton0.kira.suppliers.KiraProvider
import com.popovanton0.kira.suppliers.base.SupplierBuilder
import com.popovanton0.kira.suppliers.boolean
import com.popovanton0.kira.suppliers.compound.GeneratedKiraScopeWithImpls
import com.popovanton0.kira.suppliers.compound.injector
import com.popovanton0.kira.suppliers.kira
import external_functions.ExampleFunction1
import kotlin.Boolean
import kotlin.collections.List
import kotlin.collections.listOf

public class Kira_ExampleFunction1() : KiraProvider<ExampleFunction1Scope> {
  public override val kira: Kira<ExampleFunction1Scope> = kira(ExampleFunction1Scope()) {
    param1 = boolean(paramName = "param1")
    injector {
      ExampleFunction1(
        param1 = param1.build().currentValue(),
      )
    }
  }

}

public class ExampleFunction1Scope :
    GeneratedKiraScopeWithImpls<ExampleFunction1Scope.SupplierImplsScope>() {
  protected override val `$$$supplierImplsScope$$$`: SupplierImplsScope = SupplierImplsScope(this)

  public lateinit var param1: SupplierBuilder<Boolean>

  public override fun collectSupplierBuilders(): List<SupplierBuilder<*>> = listOf(param1, )

  public class SupplierImplsScope(
    private val scope: ExampleFunction1Scope,
  ) : GeneratedKiraScopeWithImpls.SupplierImplsScope() {
    public var param1: BooleanSupplierBuilder
      get() = scope.param1 as? BooleanSupplierBuilder ?: implChanged()
      set(`value`) {
        scope.param1 = value
      }
  }
}
